// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function valueToNumber(value) {
  return value + 2 | 0;
}

function numberToValue(number) {
  var switcher = number - 2 | 0;
  if (switcher > 12 || switcher < 0) {
    throw Caml_builtin_exceptions.not_found;
  }
  return switcher;
}

exports.valueToNumber = valueToNumber;
exports.numberToValue = numberToValue;
/* No side effect */
